### PR TITLE
Customising landing page sections

### PR DESCRIPTION
**Pull request by vascubrian**
I have worked on the image cropping,  image slider section , image gallery section, what we offers section and plus organising index.html file.
Home:
image

### CODE REVIEW

**Comment by vascubrian** [comment]
Hi @mmugisha github doesn't have html files preview , the only way you can clone repo and click on the index.html file.

**Comment by mmugisha** [comment]
@vascubrian approved. This is the new link for the Airbnb site containing the apt details: https://airbnb.com/h/pineapple-courtyard-nansana

**Review by mmugisha — APPROVED** [review]
Looking good @vascubrian

**Comment by vascubrian** [comment]
@mmugisha I will check

**Pull request merged**
